"""
World generation via spiral-outward diffusion.

Starts with a 3x3 seed of chunks, then generates new chunks by spiraling
outward. Each new chunk is generated by conditioning on its available neighbors.

Missing neighbors are filled with a MASK state (uniform distribution).
"""

import argparse
import json
from pathlib import Path

import numpy as np
import torch

from .diffusion import CategoricalDiffusion
from .palette import CHUNK_X, CHUNK_Y, CHUNK_Z, KERNEL_SIZE, NUM_BLOCK_TYPES
from .dataset import STATE_REAL, STATE_MASK, STATE_TARGET, make_state_volume
from .unet3d import ChunkUNet3D


def make_seed_chunks(num_chunks: int = 9) -> dict[tuple[int, int], np.ndarray]:
    """Generate a 3x3 grid of simple seed chunks.

    These are very basic procedural chunks: stone at the bottom, dirt, then air.
    Just enough to bootstrap generation.
    """
    seed = {}
    for dz in range(-1, 2):
        for dx in range(-1, 2):
            chunk = np.zeros((CHUNK_Y, CHUNK_Z, CHUNK_X), dtype=np.uint8)
            # Bedrock at y=0
            chunk[0, :, :] = 7  # misc_solid (bedrock)
            # Stone from y=1 to y=55
            chunk[1:56, :, :] = 1  # stone
            # Dirt from y=56 to y=62
            chunk[56:63, :, :] = 2  # dirt
            # Grass block at y=63
            chunk[63, :, :] = 2  # dirt (grass_block maps to dirt category)
            # Air above
            # (already 0)
            seed[(dx, dz)] = chunk
    return seed


def spiral_order(radius: int) -> list[tuple[int, int]]:
    """Generate chunk coordinates in a spiral order outward from (0,0).

    Skips the center 3x3 (those are the seed).
    """
    coords = []
    for r in range(2, radius + 1):
        # Top edge: z = -r, x from -r to r
        for x in range(-r, r + 1):
            coords.append((x, -r))
        # Right edge: x = r, z from -r+1 to r
        for z in range(-r + 1, r + 1):
            coords.append((r, z))
        # Bottom edge: z = r, x from r-1 to -r
        for x in range(r - 1, -r - 1, -1):
            coords.append((x, r))
        # Left edge: x = -r, z from r-1 to -r+1
        for z in range(r - 1, -r, -1):
            coords.append((-r, z))

    # Also include the ring at r=1 that isn't in the 3x3 seed
    # Actually the seed IS the 3x3 from (-1,-1) to (1,1), so r=2 is first new ring.
    # But we might need chunks just outside the seed that share edges with it.
    # Let's also add the ring between seed and r=2 -- wait, r=2 IS the next ring.
    # The seed covers (-1,-1) to (1,1). r=2 covers the ring at distance 2.
    return coords


def build_context_grid(
    world: dict[tuple[int, int], np.ndarray],
    center_cx: int,
    center_cz: int,
    device: torch.device,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Build the 3x3 input grid and state map for a target chunk.

    Args:
        world: Dict of (cx, cz) -> chunk array for all generated chunks so far.
        center_cx, center_cz: The chunk coordinate to generate.
        device: Torch device.

    Returns:
        grid_int: (1, Y, 3Z, 3X) integer tensor.
        state_vol: (1, 1, Y, 3Z, 3X) float tensor.
    """
    grid = np.zeros(
        (CHUNK_Y, KERNEL_SIZE * CHUNK_Z, KERNEL_SIZE * CHUNK_X), dtype=np.int64
    )
    state_map = np.full((KERNEL_SIZE, KERNEL_SIZE), STATE_MASK, dtype=np.float32)

    for gz in range(KERNEL_SIZE):
        for gx in range(KERNEL_SIZE):
            dz = gz - 1
            dx = gx - 1
            cx, cz = center_cx + dx, center_cz + dz
            z_start = gz * CHUNK_Z
            x_start = gx * CHUNK_X

            if dx == 0 and dz == 0:
                # Target chunk -- will be filled with noise by the diffusion process
                state_map[gz, gx] = STATE_TARGET
            elif (cx, cz) in world:
                grid[:, z_start : z_start + CHUNK_Z, x_start : x_start + CHUNK_X] = (
                    world[(cx, cz)]
                )
                state_map[gz, gx] = STATE_REAL
            # else: stays MASK (zeros in grid, STATE_MASK in state_map)

    grid_t = torch.from_numpy(grid).unsqueeze(0).to(device)

    state_map_t = torch.from_numpy(state_map).unsqueeze(0).to(device)
    state_vol = make_state_volume(state_map_t)

    return grid_t, state_vol


def generate_world(
    model: ChunkUNet3D,
    diffusion: CategoricalDiffusion,
    radius: int = 5,
    temperature: float = 0.8,
    device: torch.device = torch.device("cuda"),
    step_callback=None,
    chunk_callback=None,
) -> dict[tuple[int, int], np.ndarray]:
    """Generate a world by spiral expansion from a seed.

    Args:
        model: Trained U-Net model.
        diffusion: Diffusion process.
        radius: How far to expand (total world will be ~(2r+1)^2 chunks).
        temperature: Sampling temperature.
        device: Torch device.
        step_callback: Called at each diffusion step with (chunk_coord, timestep, x_t).
        chunk_callback: Called when a chunk is complete with (chunk_coord, chunk_data).

    Returns:
        Dict of (cx, cz) -> numpy array for all chunks.
    """
    model.eval()

    # Start with seed
    world = make_seed_chunks()
    print(f"Seed: {len(world)} chunks")

    if chunk_callback:
        for coord, data in world.items():
            chunk_callback(coord, data)

    # Generate outward in spiral
    order = spiral_order(radius)
    print(f"Generating {len(order)} chunks in spiral order...")

    for i, (cx, cz) in enumerate(order):
        if (cx, cz) in world:
            continue

        print(f"  [{i + 1}/{len(order)}] Generating chunk ({cx}, {cz})...")

        grid_int, state_vol = build_context_grid(world, cx, cz, device)

        def _step_cb(t, x_t):
            if step_callback:
                step_callback((cx, cz), t, x_t[0].cpu().numpy())

        chunk = diffusion.sample(
            model,
            grid_int,
            state_vol,
            temperature=temperature,
            callback=_step_cb,
        )

        chunk_np = chunk[0].cpu().numpy().astype(np.uint8)
        world[(cx, cz)] = chunk_np

        if chunk_callback:
            chunk_callback((cx, cz), chunk_np)

    return world


def save_world(world: dict[tuple[int, int], np.ndarray], output_dir: str | Path):
    """Save a generated world to disk."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    for (cx, cz), chunk in world.items():
        np.save(output_dir / f"chunk_{cx}_{cz}.npy", chunk)

    # Save metadata
    meta = {
        "chunks": [[cx, cz] for cx, cz in world.keys()],
        "palette_size": NUM_BLOCK_TYPES,
        "chunk_shape": [CHUNK_Y, CHUNK_Z, CHUNK_X],
    }
    with open(output_dir / "meta.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(f"Saved {len(world)} chunks to {output_dir}")


def main():
    parser = argparse.ArgumentParser(description="Generate world from trained model")
    parser.add_argument(
        "--checkpoint", type=str, required=True, help="Path to model checkpoint"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./generated_world",
        help="Output directory for generated chunks",
    )
    parser.add_argument(
        "--radius", type=int, default=5, help="World radius in chunks from center"
    )
    parser.add_argument(
        "--temperature", type=float, default=0.8, help="Sampling temperature"
    )
    parser.add_argument(
        "--num-timesteps",
        type=int,
        default=200,
        help="Number of diffusion timesteps (must match training)",
    )
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load model
    print(f"Loading checkpoint: {args.checkpoint}")
    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    train_args = ckpt.get("args", {})

    model = ChunkUNet3D(
        base_channels=train_args.get("base_channels", 48),
        block_embed_dim=train_args.get("block_embed_dim", 16),
    ).to(device)
    model.load_state_dict(ckpt["model"])
    model.eval()

    diffusion = CategoricalDiffusion(
        num_timesteps=args.num_timesteps,
        noise_schedule="cosine",
        device=device,
    )

    world = generate_world(
        model,
        diffusion,
        radius=args.radius,
        temperature=args.temperature,
        device=device,
    )
    save_world(world, args.output_dir)


if __name__ == "__main__":
    main()
